apiVersion: v1
kind: Namespace
metadata:
  name: infra-mind
  labels:
    name: infra-mind
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-mind-staging
  labels:
    name: infra-mind-staging
    environment: staging
